[package]

name = "rdb"
version = "1.0.0-alpha"
authors = ["Jan-Erik Rediger <badboy@fnordig.de>"]

keywords = ["redis", "database"]
description = "Fast and efficient RDB parsing utility"

readme = "README.md"
license = "MIT"

homepage = "http://rdb.fnordig.de/"
documentation = "http://rdb.fnordig.de/doc/rdb/"
repository = "https://github.com/badboy/rdb-rs"

[dependencies]
lzf = "0.3.0"
getopts = "0.2.14"
rustc-serialize = "0.3.16"
regex = "0.1.41"
byteorder = "0.3.13"
