[package]

name = "rdb"
version = "0.0.1"
authors = ["Jan-Erik Rediger <badboy@archlinux.us>"]

[[bin]]
name = "rdb"
path = "src/main.rs"
doc  = false

[dependencies]
lzf = "*"
getopts = "*"
rustc-serialize = "*"
regex = "*"
byteorder = "*"
